model:
  name: cae
  latent_dim: 8
  hidden_units: [32, 32]
  beta: 0
  dropout: 0.0

optim:
  optimizer: Adam
  lr: 0.0001

training:
  cache_freq: 10000
  eval_freq: 500
  logs_freq: 50
  n_iters: 250000

