model:
  name: scgen
  latent_dim: 8
  hidden_units: [32, 32]
  beta: 0
  dropout: 0.05

optim:
  optimizer: Adam
  lr: 0.001

training:
  cache_freq: 1000
  eval_freq: 500
  logs_freq: 50
  n_iters: 100000

