data:
  type: cell
  source: unst
  target: LPS
  condition: condition
  path: datasets/scrna-crossspecies/hvg-top1k-train-only.h5ad

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: condition 
  name: train_test_eval
  test_size: 500
  eval_size: 500
  random_state: 0
  subset:
    species: mouse
