data:
  type: cell
  source: control
  target: panobinostat
  condition: perturbation
  path: datasets/scrna-gbm/hvg-top1k-train-only.h5ad

dataloader:
  batch_size: 128
  shuffle: true

datasplit:
  holdout: PW034
  key: sample 
  groupby: ['sample', 'perturbation']
  name: toggle_ood
  mode: ood
  test_size: 500
  random_state: 0
  subset:
    sample: ['PW034', 'PW036', 'PW040', 'PW051', 'PW053']
