data:
  type: cell
  source: control
  condition: drug
  path: /home/xiejc/Workspace/meta_perturb/datasets/scrna-sciplex3/sciplex.h5ad

datasplit:
    groupby: drug 
    name: train_test
    test_size: 0.2
    random_state: 0

dataloader:
    batch_size: 256
    shuffle: true

